### ISSUE TITLE
怎么样改成可以搜索自己需要的省份

### ISSUE THREAD

**Issue by mlzlzj** [MemoryCollection/IPTV#10]
大佬，要怎么样改一下才能搜索到自己想要的省份或城市的，比喻我需要湖南的，city_list = ["湖南", "广东", "广西"]这里已经改了，但显示还是显示
测试 UDPxy 代理（异步）
IP 可用：http://114.252.238.87:8000 (省份: 北京联通)
IP 可用：http://114.246.182.66:4022 (省份: 北京联通)
IP 可用：http://125.34.219.161:8000 (省份: 北京联通)
IP 可用：http://221.221.162.225:8888 (省份: 北京联通)
IP 可用：http://101.17.112.86:8888 (省份: 河北联通)
IP 可用：http://111.196.135.75:8686 (省份: 北京联通)
IP 可用：http://110.248.147.40:8888 (省份: 河北联通)
IP 可用：http://60.2.190.206:4000 (省份: 河北联通)
IP 可用：http://60.5.223.24:4000 (省份: 河北联通)
IP 可用：http://123.118.59.153:8686 (省份: 北京联通)
IP 可用：http://114.252.235.176:8000 (省份: 北京联通)
IP 可用：http://112.80.121.47:8118 (省份: 江苏联通)
IP 可用：http://221.221.167.14:8888 (省份: 北京联通)
IP 可用：http://114.248.183.109:4000 (省份: 北京联通)
IP 可用：http://60.5.223.30:4000 (省份: 河北联通)
IP 可用：http://60.4.9.252:18888 (省份: 河北联通)
IP 可用：http://114.252.114.248:8445 (省份: 北京联通)
IP 可用：http://123.118.159.0:8686 (省份: 北京联通)
IP 可用：http://221.218.15.95:8888 (省份: 北京联通)
IP 可用：http://123.113.237.160:8888 (省份: 北京联通)
IP 可用：http://123.116.141.214:8000 (省份: 北京联通)
IP 可用：http://123.117.239.226:8089 (省份: 北京联通)
IP 可用：http://123.117.237.15:8680 (省份: 北京联通)
IP 可用：http://111.196.129.152:20000 (省份: 北京联通)
IP 可用：http://114.254.37.1:18888 (省份: 北京联通)
IP 可用：http://123.116.142.185:8000 (省份: 北京联通)
IP 可用：http://111.196.75.15:8888 (省份: 北京联通)
IP 可用：http://222.128.86.76:8133 (省份: 北京联通)
IP 可用：http://111.199.234.10:18888 (省份: 北京联通)
IP 可用：http://123.117.238.92:8089 (省份: 北京联通)
IP 可用：http://221.218.15.95:8000 (省份: 北京联通)
IP 可用：http://123.114.62.187:8000 (省份: 北京联通)
IP 可用：http://123.113.187.204:8000 (省份: 北京联通)
IP 可用：http://114.241.168.152:8888 (省份: 北京联通)
IP 可用：http://123.117.235.44:8089 (省份: 北京联通)
IP 可用：http://222.129.139.229:8888 (省份: 北京联通)
IP 可用：http://114.254.24.139:18888 (省份: 北京联通)
IP 可用：http://111.199.194.80:4022 (省份: 北京联通)
IP 可用：http://175.171.189.62:18888 (省份: 辽宁联通)
IP 可用：http://121.29.84.176:18888 (省份: 河北联通)
IP 可用：http://60.5.223.35:4000 (省份: 河北联通)
IP 可用：http://60.7.56.22:4000 (省份: 河北联通)
IP 可用：http://60.7.62.223:4000 (省份: 河北联通)
IP 可用：http://60.7.56.33:4000 (省份: 河北联通)
IP 可用：http://60.5.223.46:4000 (省份: 河北联通)
IP 可用：http://60.7.56.27:4000 (省份: 河北联通)
IP 可用：http://60.5.223.107:8888 (省份: 河北联通)
IP 可用：http://222.129.139.91:8888 (省份: 北京联通)
数据已成功写入文件：data/iplist.json
Progress: 1 / 56
Progress: 2 / 56
Progress: 3 / 56
这些，根本没有搜索到我需要的，请教一下要改哪里才行。

**Comment by MemoryCollection** [comment]
iplist.json

把这个文件清空了，代码是追加不是覆盖，所以只要之前搜索到的ip还能用就不会删除。
