### ISSUE TITLE
请加入一个可以搜索到湖南的组播的代码

### ISSUE THREAD

**Issue by mlzlzj** [MemoryCollection/IPTV#11]
请在这个代码加入一个可以搜索到湖南的组播的频道列表功能吧，我需要湖南的，大佬！

**Comment by MemoryCollection** [comment]
的等等，我笔记本放公司了

**Comment by MemoryCollection** [comment]
README.md或者看这个文件介绍。
之前的代码应该还能用，在分支里

**Comment by MemoryCollection** [comment]
搞明白了吗  没懂我今天弄下

**Comment by MemoryCollection** [comment]
[湖南电信.txt](https://github.com/user-attachments/files/17973195/default.txt)
[湖南联通.txt](https://github.com/user-attachments/files/17973196/default.txt)
这两个文件，放在udp文件夹内，就可以了。
