### ISSUE TITLE
获取不到频道列表了

### ISSUE THREAD

**Issue by mlzlzj** [MemoryCollection/IPTV#3]
大佬啊，应该是网站结构变了呢，现在爬不到数据了

**Comment by MemoryCollection** [comment]
![image](https://github.com/user-attachments/assets/be8ea6b6-425a-4697-a439-7429d14bff26)
![image](https://github.com/user-attachments/assets/90eea2dd-9d66-4b49-9928-c696ea86bab7)
没有问题啊,可以正常爬取,你看看是不是你那边网的问题
