### ISSUE TITLE
没有更新

### ISSUE THREAD

**Issue by mlzlzj** [MemoryCollection/IPTV#4]
我是直接fork你的仓库的，你的没有更新我的就一样不行了，我以为是代码原因，我在本地运行可以的，但还是希望能升级代码解决可以获取[www.erbao1981.top:8188] [频道数：282]  存活22天  湖南电信 这类域名下的频道列表。想看湖南组播太难了。

**Comment by MemoryCollection** [comment]
把搜索的关键词改成湖南不行吗?

我是在服务器定时爬取的,最近没同步到GitHub,我修改同步下

**Comment by mlzlzj** [comment]
肯定是修改为搜索湖南的，但湖南的组播源特别少，只有几个域名和ip下有，而且要翻页，并且很多是失效的，所以希望能升级代码可以解析域名下的频道列表和可以搜索多页（3页就足够了），现在只搜索第一页的不够。
