### ISSUE TITLE
怎么样设置才能获取到频道列表

### ISSUE THREAD

**Issue by mlzlzj** [MemoryCollection/IPTV#5]
大佬，请问一下怎么样设置才能在github上自动运行后获取到频道列表，我现在可以通过工作流定时运行，但就是获取不到频道列表，都是空的，在电脑本地运行可以获取到频道列表，请大佬指点一下怎么样才能在github上面获取到频道列表。

**Comment by MemoryCollection** [comment]
https://github.com/ssili126/tv

可以用他的代码，他的已经设置好了

**Comment by MemoryCollection** [comment]
我自己这个，我也没找到原因，我也是哥小菜鸡，自学的，懂的不多

**Comment by MemoryCollection** [comment]
也可以用这个：https://raw.gitmirror.com/MemoryCollection/IPTV/main/itvlist.txt
我用北京服务器测速的，9个小时更新一次
