### ISSUE TITLE
能把最开始的老版放上来吗

### ISSUE THREAD

**Issue by mlzlzj** [MemoryCollection/IPTV#7]
大佬能不能把最初的老版本放上来啊，那个版本可以同时获取到组播和酒店，湖南的组播实在是少，而且没有rtp的，最开始你那个版本就可以保留udp的组播和酒店源，请把老的版本也放上来吧，谢谢了

**Comment by MemoryCollection** [comment]
http://www.foodieguide.com/iptvsearch/hoteliptv.php
http://tonkiang.us/hoteliptv.php

两个地址好像都爬不了了，你可以手动试试看。能搜到ip但看不到具体频道

**Comment by mlzlzj** [comment]
http://tonkiang.us/hoteliptv.php这个死了，应该过一阵子改了网页结构又会好的，爬的人太多就会换一下结构，经常是这样搞的，http://www.foodieguide.com/iptvsearch/hoteliptv.php这个可以搜到ip和频道，我还是想要你原来最开始放在上面的老版本，那个可以扫到酒店源的

**Comment by MemoryCollection** [comment]
![image](https://github.com/user-attachments/assets/c5aa1abc-d9ac-4a53-a830-74382b09d509)
能搜索da到，但是点开不行

**Comment by MemoryCollection** [comment]
等过一段时间看能不能变好，现在改成用selenium，如果能继续使用，我回头改成可以翻页的，到时候湖南的就多了

**Comment by MemoryCollection** [comment]
更新了，你看看怎么样？现在可以翻页了。需要使用selenium  你会配置不？
