### ISSUE TITLE
哥，我想找上海的，我把area = ["上海", "山东"]改为上海了，怎么出来的归属地还都是北京的吖，要改哪里，请教一下，我萌新

### ISSUE THREAD

**Issue by xiaojie-001** [MemoryCollection/IPTV#8]

**Comment by MemoryCollection** [comment]
area = ["上海", "山东"]

这么改是对的，你可以114行，添加一行代码，print(f"正在爬取城市： {write_json_file} ")

看看他是不是搜索的上海，在一个，你看下data/Origfile.json 这里都是历史爬取的，新爬取不会覆盖而是在这个基础上追加的。
