### ISSUE TITLE
能否修改一下运行方式

### ISSUE THREAD

**Issue by mlzlzj** [MemoryCollection/IPTV#9]
大佬，能不能改成像原来开始那样的运行方式，比喻我想爬取湖南的，就显示爬取到的ip和每个ip下爬取到的频道列表，然后对这些频道列表进行过滤统一名称，测速排序分组，那样就很直观，知道需要爬取的地区和频道，现在就一个检测进度，啥也不知道，而且获取到的频道有没有也不知道

**Comment by MemoryCollection** [comment]
还能用？我还以为没法爬了那

**Comment by MemoryCollection** [comment]
![Screenshot_2024-11-23-20-22-50-608_com lemurbrowser exts](https://github.com/user-attachments/assets/c5a88e38-ae78-4c8e-9e70-6fcbb1223a69)
好多ip都不能用，现在也是有提示的，只是会检测，如果之前的可用频道超过600个就不会爬新的，需要每次都爬。你可以修改下检测，把他删掉

**Comment by MemoryCollection** [comment]
if int(ip_data["详情"]["iptv"]) < 600:

把这行代码删掉，删不明白就600改成1，这样每次执行都会爬去新的ip
